SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `BATIMENT` (
  `idBatiment` int(11) NOT NULL,
  `Adresse` varchar(255) NOT NULL,
  `codePostal` varchar(10) NOT NULL,
  `ville` varchar(70) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `COPROPRIETAIRE` (
  `idCopropriete` int(11) NOT NULL,
  `idBatiment` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `COPROPRIETE` (
  `idCopropriete` int(11) NOT NULL,
  `nom` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `LOT` (
  `idLot` int(11) NOT NULL,
  `idBatiment` int(11) NOT NULL,
  `libelle` varchar(60) NOT NULL,
  `etage` int(11) NOT NULL,
  `localisation` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `OCCUPANT` (
  `idLot` int(11) NOT NULL,
  `idPersonne` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PERSONNE` (
  `idPersonne` int(11) NOT NULL,
  `nom` varchar(50) NOT NULL,
  `prenom` varchar(30) NOT NULL,
  `Adresse` varchar(255) NOT NULL,
  `codePostal` varchar(10) NOT NULL,
  `ville` varchar(70) NOT NULL,
  `tel` varchar(20) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PROPRIETAIRE` (
  `idLot` int(11) NOT NULL,
  `idPersonne` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE `BATIMENT`
  ADD PRIMARY KEY (`idBatiment`);

ALTER TABLE `COPROPRIETAIRE`
  ADD PRIMARY KEY (`idBatiment`);

ALTER TABLE `COPROPRIETE`
  ADD PRIMARY KEY (`idCopropriete`);

ALTER TABLE `LOT`
  ADD PRIMARY KEY (`idLot`);

ALTER TABLE `OCCUPANT`
  ADD PRIMARY KEY (`idLot`,`idPersonne`);

ALTER TABLE `PERSONNE`
  ADD PRIMARY KEY (`idPersonne`);

ALTER TABLE `PROPRIETAIRE`
  ADD PRIMARY KEY (`idLot`,`idPersonne`);


ALTER TABLE `BATIMENT`
  MODIFY `idBatiment` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
ALTER TABLE `COPROPRIETE`
  MODIFY `idCopropriete` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
ALTER TABLE `LOT`
  MODIFY `idLot` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
ALTER TABLE `PERSONNE`
  MODIFY `idPersonne` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
